title: 'b2a3e8.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/fur2"
url: "https://fur2.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

# Build settings
markdown: kramdown


# Example Site settings

#google_analytics: UA-NNNNNNNN-N

footer: 'follow us on <a href="https://github.com/fur2">Github</a>'

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
